### PR TITLE
fixed mid-button line break, issue #4

### PR DESCRIPTION
**Pull request by frozenpandaman**
fixed rides.css, precompiled assets to update application.css

### CODE REVIEW

**Comment by KentShikama** [comment]
@frozenpandaman Precompiled assets should be in the .gitignore (public/assets/). I'm surprised it already isn't that way.

**Comment by frozenpandaman** [comment]
@theworldbright yeah, i was surprised to see all those files there as well. oh well, the issue should be fixed now. i could update the .gitignore too, though?

**Comment by KentShikama** [comment]
Yeah update the .gitignore and remove all the committed asset files.

**Comment by KentShikama** [comment]
I could just pick out your diff on the `app/assets/stylesheets/rides.css.scss` of course, if you are too busy. The issue itself is fixed indeed :+1:

**Comment by frozenpandaman** [comment]
done! hopefully all's good now.

**Comment by KentShikama** [comment]
Merged as 8ee1930 and c2cd744

Thanks Eli!

**Comment by mattdahl** [comment]
Thanks a lot, Eli! @frozenpandaman

**Pull request closed without merging**
