### PR TITLE
Change url of 'Book a Cab'

### PR DESCRIPTION
**Pull request by ZiqiXiong**

### CODE REVIEW

**Comment by alokedesai** [comment]
@ZiqiXiong I was going to make a nit to remove all the spacing diffs but I actually think all the spacing changes were probably the right choice here, :+1:. In the future please tag all of us individually or tag @aspc/digital-media-and-programming-group

**Comment by ZiqiXiong** [comment]
Sure!

**Comment by KentShikama** [comment]
Merged as 765c663

**Comment by mattdahl** [comment]
@ZiqiXiong You can reference the issue that you're addressing in the commit message in the future, e.g. "resolves #3" or "fixes #3" so the commit history itself preserves a link to the related issue, instead of having to manually check the associated PR if someone wants more information

**Comment by ZiqiXiong** [comment]
@mattdahl  Got it

**Pull request closed without merging**
