### PR TITLE
Fix change of "Flight" to "Shuttle"

### PR DESCRIPTION
**Pull request by KentShikama**
Earlier I had changed the word "flight" to "shuttle" in a HAML template that was unused. This commit changes the word in a way that reflects in the UI.

@aspc/digital-media-and-programming-group

### CODE REVIEW

**Comment by mattdahl** [comment]
Looks fine. The removed HAML template doesn't serve any purpose at all?

**Comment by KentShikama** [comment]
The controller corresponding to those HAML templates was removed in 98d9c05, specifically [here](https://github.com/aspc/5C-Ride-Share/commit/98d9c0547b435387d20b5a08b9dc007e24c2f7dd#diff-915c272ea05fa253598c804d629c72f1L137).

**Comment by mattdahl** [comment]
Very good. How do you think we should handle updating the flight data on prod that has already been entered under the "flight arrival time" assumption? I.e. there are some rides from LAX next week (http://5crideshare.com/rides/airport?id=4) that might get messed up if we switch their times to reference "shuttle time" instead of "flight time". Should we tell those people to update their listings themselves? Or wait until after fall break to deploy maybe?

**Comment by alokedesai** [comment]
@mattdahl @theworldbright Why not toggle the text based on when the ride was created?

**Comment by alokedesai** [comment]
(Besides that LGTM)

**Comment by KentShikama** [comment]
Waiting until after Fall break sounds good to me.

@alokedesai Do you mean for [this page](http://5crideshare.com/rides/airport?id=4)?

**Comment by alokedesai** [comment]
Oh whoops, I meant for a ride-specific page: http://5crideshare.com/rides/2426 since even changing that from shuttle time to flight time is confusing while a ride exists. +1 to waiting until after fall break on the generic airport page though.

**Comment by mattdahl** [comment]
How can we decouple the label on the ride-specific page and the one on the generic-page page though? For instance, if we implement that toggle but keep the generic-page as "Flight Time" until Fall Break for all rides, won't any new rides created between now and Fall Break still have label mismatch? I.e. For those newly created rides, users will see the time labeled as "Flight Time" on the generic-page but as "Shuttle Time" on the ride-specific page.

I think such a toggle might too messy. I think we should just wait until right after Fall Break to deploy this, at which time hopefully new ride creation will be at its nadir, before the Thanksgiving rush.

**Comment by KentShikama** [comment]
> I think we should just wait until right after Fall Break to deploy this, at which time hopefully new ride creation will be at its nadir, before the Thanksgiving rush.

Yeah, we could just give out some manual notifications that we have changed the label if it is less than 10 or so.

**Comment by alokedesai** [comment]
Yeah, sorry for the confusion, I definitely agree with you guys on this.

**Comment by KentShikama** [comment]
Should I make the following comment to any existing ride?

---

The "Flight Arrival Time" label has been changed to "Shuttle Arrival Time" for the following reasons:
- There is a discrepancy between when your flight arrives and when you exit the airport gates across flights. International flights require a lot longer to exit than domestic flights.
- Some people interpret "Flight Arrival Time" as "Shuttle Arrival Time." On the ride I booked back in spring, I had two people interpret the label literally and two people interpret the label as "Shuttle Arrival Time." This confusion is further complicated by the fact that the "To LAX/Ontario" options on 5C Ride Share provide a buffer time between the flight time and the shuttle time.

Please adjust your "Shuttle Arrival Time" if necessary. Thanks and pardon for any inconveniences.

**Comment by mattdahl** [comment]
That is too confusing imo. You can literally just say "5C Ride Share made a small change to how it displays shuttle arrival times. Please double-check and adjust your "Shuttle Arrival Time" if necessary. Thanks and pardon for any inconveniences." We needn't bother them with the rationale.

Also, I am confused now too. Are pages like http://5crideshare.com/rides/2472 still supposed to be showing the "flight time" label?

**Comment by KentShikama** [comment]
> Also, I am confused now too. Are pages like http://5crideshare.com/rides/2472 still supposed to be showing the "flight time" label?

Yeah that was not in my original calculations. The "To" rides have both the shuttle time and the flight time. The current intermediate state of showing "shuttle time" on the list view and "flight time" on the single view is probably the most confusing option. I'll patch together a hotfix to change that.

**Comment by KentShikama** [comment]
I pushed the hotfix as 68b48a8 and abd015c.

I've made the following comment on all currently existing rides

---

The "Flight Arrival Time" label has been changed to "Shuttle Arrival Time." Please double-check and adjust your "Shuttle Arrival Time" if necessary. Thanks and pardon for any inconveniences.

**Comment by mattdahl** [comment]
Cool, looks good

**Pull request merged**
